/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import conexao.AgendamentoConexao;
import conexao.moduloConexao;
import Model.Agendamento;
import Utils.*;

public class Agenda extends javax.swing.JFrame {
    public Agenda() {
        initComponents();
        Core.centerWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id1 = new javax.swing.JLabel();
        txt_id3 = new javax.swing.JLabel();
        txt_id5 = new javax.swing.JLabel();
        txt_id4 = new javax.swing.JLabel();
        txt_id6 = new javax.swing.JLabel();
        txt_id7 = new javax.swing.JLabel();
        txt_id2 = new javax.swing.JLabel();
        jhora = new javax.swing.JTextField();
        jdata = new javax.swing.JTextField();
        btn_agendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtext_observacao = new javax.swing.JTextArea();
        jprofissional = new javax.swing.JComboBox<>();
        jtiposervico = new javax.swing.JComboBox<>();
        jcliente = new javax.swing.JTextField();
        painel = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_id1.setForeground(new java.awt.Color(255, 255, 255));
        txt_id1.setText("Profissional");
        getContentPane().add(txt_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 170, 60));

        txt_id3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_id3.setForeground(new java.awt.Color(255, 255, 255));
        txt_id3.setText("Hora");
        getContentPane().add(txt_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 80, 20));

        txt_id5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_id5.setForeground(new java.awt.Color(255, 255, 255));
        txt_id5.setText("Data");
        getContentPane().add(txt_id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 50, 20));

        txt_id4.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        txt_id4.setForeground(new java.awt.Color(255, 255, 255));
        txt_id4.setText("Agenda");
        getContentPane().add(txt_id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 150, 50));

        txt_id6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_id6.setForeground(new java.awt.Color(255, 255, 255));
        txt_id6.setText("Cliente");
        getContentPane().add(txt_id6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 20));

        txt_id7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_id7.setForeground(new java.awt.Color(255, 255, 255));
        txt_id7.setText("Observação:");
        getContentPane().add(txt_id7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, 20));

        txt_id2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_id2.setForeground(new java.awt.Color(255, 255, 255));
        txt_id2.setText("Tipo de Serviço");
        getContentPane().add(txt_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 60));
        getContentPane().add(jhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 150, 40));
        getContentPane().add(jdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, 40));

        btn_agendar.setText("Agendar");
        btn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 930, 40));

        jtext_observacao.setColumns(20);
        jtext_observacao.setRows(5);
        jScrollPane1.setViewportView(jtext_observacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 610, 270));

        jprofissional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Luis Renato", "Acacio de Lima", "Winicius Santos" }));
        getContentPane().add(jprofissional, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 310, 40));

        jtiposervico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Corte - R$ 40,00", "Corte + Barba - R$ 70, 00", "Barba - R$ 30,00" }));
        jtiposervico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtiposervicoActionPerformed(evt);
            }
        });
        getContentPane().add(jtiposervico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 310, 40));

        jcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclienteActionPerformed(evt);
            }
        });
        getContentPane().add(jcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 310, 40));

        painel.setForeground(new java.awt.Color(153, 255, 0));
        painel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        painel.setText("jLabel2");
        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1170, 560));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        fundo.setText("jLabel1");
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtiposervicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtiposervicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtiposervicoActionPerformed

    private void btn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarActionPerformed
        String profissional = jprofissional.getSelectedItem().toString();
        String data = jdata.getText().toString();
        String hora = jhora.getText().toString();
        String cliente = jcliente.getText().toString();
        String tipoServico = jtiposervico.getSelectedItem().toString();
        String textObservacao = jtext_observacao.getText().toString();
        
        Agendamento a = new Agendamento(cliente, tipoServico, data, profissional, hora, textObservacao);
        
        moduloConexao mconexao = new moduloConexao();
        AgendamentoConexao aconexao = new AgendamentoConexao(mconexao.abrirConexao());
        aconexao.agendar(a);
        mconexao.fecharConexao();
        
        jcliente.getText();
        jprofissional.setSelectedItem("");
        jdata.getText();
        jhora.getText();
        jtiposervico.setSelectedItem("");
        jtext_observacao.getText();
        jprofissional.requestFocus(); 
       
        
    }//GEN-LAST:event_btn_agendarActionPerformed

    private void jclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agendar;
    private javax.swing.JLabel fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcliente;
    private javax.swing.JTextField jdata;
    private javax.swing.JTextField jhora;
    private javax.swing.JComboBox<String> jprofissional;
    private javax.swing.JTextArea jtext_observacao;
    private javax.swing.JComboBox<String> jtiposervico;
    private javax.swing.JLabel painel;
    private javax.swing.JLabel txt_id1;
    private javax.swing.JLabel txt_id2;
    private javax.swing.JLabel txt_id3;
    private javax.swing.JLabel txt_id4;
    private javax.swing.JLabel txt_id5;
    private javax.swing.JLabel txt_id6;
    private javax.swing.JLabel txt_id7;
    // End of variables declaration//GEN-END:variables




}
